name: painter2
description: A fork of the original painter plugin that adds some missing functionality.
version: 1.0.1
author: ja2375 <webmaster@javi-h.com>
homepage: https://github.com/ja2375/painter2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
